spring.application.name=demo
server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/travelagency_db?useSSL=false&serverTimezone=UTC
spring.datasource.username=felipe
spring.datasource.password=Gatitaratonera1.

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

debug=true

spring.security.oauth2.client.registration.keycloak.client-id=travelAgency-backend
spring.security.oauth2.client.registration.keycloak.client-secret=8wFHKVa431JYaWPniAglwYaKMyFt124X
spring.security.oauth2.client.registration.keycloak.scope=openid,profile,email
spring.security.oauth2.client.registration.keycloak.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.keycloak.redirect-uri=http://localhost:8081/login/oauth2/code/keycloak

spring.security.oauth2.client.provider.keycloak.issuer-uri=http://localhost:8080/realms/travelAgency

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/travelAgency